/**
 * "Can pressing this spell help somebody other than the caster?" — one
 * predicate, official data first.
 *
 * GH #28 (2026-08-22, user report): the coach told a Priest they should have
 * pressed Desperate Prayer when a TEAMMATE was dying. Desperate Prayer heals
 * the caster and nobody else. Nothing in the data tables was wrong — the
 * accusation-producing predicates simply had no "does it reach an ally"
 * dimension, so every Defensive-tagged cooldown in the kit counted as an
 * answer to a teammate's crisis (measured: 126 such candidate events in 80
 * matches, 46 of them Desperate Prayer).
 *
 * Source of truth: DB2 `SpellEffect.ImplicitTarget_0/_1`, generated by
 * `scripts/datagen/genSpellTargeting.ts` (that file documents the derivation,
 * the two traps it encodes — dummy effect rows and the one
 * `EffectTriggerSpell` hop — and the two-directional ground-truth assertion
 * that runs before it writes anything).
 *
 * Why official rather than a hand list: the only list that expressed this fact
 * (`externalDefensiveSpellIds`, 14 entries) is curated, and CLAUDE.md's
 * Curated-List Completeness Rule says such a list can only prove the absence
 * of false positives. It was in fact incomplete in the ally-reaching
 * direction — Tranquility (740), Divine Hymn (64843) and Aura Mastery (31821)
 * all reach allies and none of them were in it. A naive "not in the external
 * list ⇒ self-only" fix would therefore have silently killed correct coaching
 * on those three (measured: 12 events in the same 80-match sample).
 *
 * The curated list stays as a FLOOR, not as the definition: an id the official
 * table has no row for (never mined, or a brand-new spell) still counts as
 * ally-reaching when the list names it.
 */
import spellIdLists from "./spellIdLists";
import { SPELL_REACHES_OTHERS_GENERATED } from "./spellTargetingGenerated";

const CURATED_ALLY_CASTABLE = new Set<string>(
  spellIdLists.externalDefensiveSpellIds as string[],
);

/**
 * True when at least one of the spell's official effects reaches a friendly
 * unit other than the caster — targeted externals (Pain Suppression), party /
 * raid-wide effects (Rallying Cry, Power Word: Barrier, Aura Mastery) and
 * ally-healing channels (Tranquility, Divine Hymn) all qualify.
 *
 * False for personal defensives (Desperate Prayer, Ice Block, Shield Wall …)
 * — pressing them cannot help the teammate who is dying, so no candidate may
 * cite them as an unspent answer to somebody else's crisis.
 *
 * Deliberately NOT the same predicate as `isAllyCastableDefensive`
 * (cooldowns.ts), which answers the narrower "can I target it ON an ally"
 * question used for external-throwing advice; an area effect like Rallying Cry
 * reaches allies without being castable on one. Both are registered in
 * docs/predicate-index.md.
 */
export function reachesAlly(spellId: string): boolean {
  return (
    SPELL_REACHES_OTHERS_GENERATED()[spellId] === true ||
    CURATED_ALLY_CASTABLE.has(spellId)
  );
}

/** True only when the official table actually knows this id (absent = "no
 *  official effect row", which every consumer must treat as unknown rather
 *  than as "self-only"). Exported for the completeness test, which asserts
 *  every Defensive-tagged cooldown in `classMetadata` is covered. */
export function hasOfficialTargeting(spellId: string): boolean {
  return SPELL_REACHES_OTHERS_GENERATED()[spellId] !== undefined;
}
